### ISSUE TITLE
Unterschiedliche Auflösungen zur Auswahl hinzufügen

### ISSUE THREAD

**Issue by osae83** [codefog/contao-instagram#1]
Über die Api gibt es unterschiedliche Auflösungen die man mit in der Modulkonfiguration packen könnte

thumbnail ->width: 150, height: 306
low_resolution ->  width: 306, height: 306
standard_resolution -> width: 612, height: 612

z. B.:
`<?php  `
 `$item['images']['thumbnail']['url'] `
`$item['images']['thumbnail'] ['width']  `
` $item['images']['thumbnail']['height']  `
 `.... `
 `<img src="<?= $item['images']['thumbnail']['url'] ?>" alt="<?= specialchars($item['caption']['text']) ?> width="<?= $item['images']['thumbnail']['width'] ?>" height="<?= $item['images']['thumbnail']['height'] ?>"> `

Gruß Olli

**Comment by qzminski** [comment]
Sorry, I do not speak German. Can you explain your issue in English?

**Comment by osae83** [comment]
Ok I'll try it
topic:  Add different resolutions to the module setting
----
Via the Instagram-API there are different resolutions that could be packed in the module configuration

**Comment by osae83** [comment]
And you could also integrate the following template -> gallery_default.html5
This allows the Instagram images to adapt immediately to the contao standard gallery and is relatively easy to adjust.

**Comment by qzminski** [comment]
Are you able to provide a pull request for this feature?

**Comment by qzminski** [comment]
An option to download images was implemented in 530ee9e.
