### ISSUE TITLE
No connection to Instagram when date format isn't set correctly

### ISSUE THREAD

**Issue by planepix** [codefog/contao-instagram#12]
Hi Kamil,

yesterday i installed the Instagram bundle, generated die Client ID and secret, got the asscess token.

After including the module into an article nothing is shown. No media also also no code when checking the source code.

Today i found out that the date format in settings wasn't set right.
` H.i instead of H:i`

After setting to H:i all media are shown in frontend.
May be a hint to build some code in to show an error or giving a hint.

Cheers
Thomas

**Comment by OMOSde** [comment]
I can´t reproduce this on a contao 4.4.21 installation.

I set 'timeFormat' to 'H.i' and 'datimFormat' to 'd.m.Y H.i' in the system settings. No date settings in the rootpage. Maybe i missunderstood something.

I tried also to delete the local stored files. But still works correct.

**Comment by planepix** [comment]
In the mentioned installation there are no settings made in the root page for date and time.

**Comment by qzminski** [comment]
Hey Thomas, thanks for reporting this but I wasn't able to reproduce this either. If this issue ever comes back please re-open the task and we'll take a look at it again.
