### ISSUE TITLE
numberOfItems = 0 breaks fe module

### ISSUE THREAD

**Issue by JessesNei** [codefog/contao-instagram#13]
Hi
after installing the module on Contao 4.7 and adding the FE-Module everything worked fine until I changed the value of field numberOfItems to 0.

After doing so there is no output for the FE-Module anymore and no error in /var/logs/.

**Comment by qzminski** [comment]
The `numberOfItems` identifies the number of images you would like to fetch. Contrary to Contao default modules, providing `0` here will result in no photos and thus you should always specify a certain amount of photos you'd like to fetch.

**Comment by JessesNei** [comment]
Okay, perfect thank you for the information.

But if this is the case the description of the field should be overwritten in the module as it tells something else.

"Hier können Sie die Gesamtzahl der Beiträge begrenzen. Geben Sie 0 ein, um alle anzuzeigen."

Is there a way to fetch all images?

**Comment by qzminski** [comment]
The maximum number of images you can fetch is 20 if you have not your Instagram app reviewed.
