### ISSUE TITLE
Graph API of Instagram deprecated, Registration disabled ?

### ISSUE THREAD

**Issue by SgnAtWork** [codefog/contao-instagram#16]
Can you tell me more about the affects of Deprecation of Instagram Graph API at the 05 of November ? I just want to register an Client, but Registration are disabled - see Attachment.

Thanx for your effors!
<img width="794" alt="Bildschirmfoto 2019-11-04 um 12 20 44" src="https://user-images.githubusercontent.com/10742053/68117575-09bc6280-fefe-11e9-9737-18ba185bb97c.png">

**Comment by fritzmg** [comment]
See https://www.instagram.com/developer/

As of October 15th, you need to use the Instagram Basic Display API via Facebook's API.

**Comment by SgnAtWork** [comment]
okay, does that affect the extension here? So the authorization is different or do I get a ClientID via the Basic API?

**Comment by fritzmg** [comment]
I think the extension needs to be completely rewritten to use Facebook's API.

**Comment by SgnAtWork** [comment]
Yes I think so too, I feared it :(

**Comment by qzminski** [comment]
@SgnAtWork would you be willing to sponsor this feature?

**Comment by SgnAtWork** [comment]
Hi Kamil, What do you think about the budget? I'm talking to the customer.

Von: Kamil Kuzminski <notifications@github.com>
Antworten an: codefog/contao-instagram <reply@reply.github.com>
Datum: Freitag, 15. November 2019 um 14:01
An: codefog/contao-instagram <contao-instagram@noreply.github.com>
Cc: Holger Neuner | 47GradNord - Agentur für Internetlösungen <neuner@47gradnord.de>, Mention <mention@noreply.github.com>
Betreff: Re: [codefog/contao-instagram] Graph API of Instagram deprecated, Registration disabled ? (#16)


@SgnAtWork<https://github.com/SgnAtWork> would you be willing to sponsor this feature?

**Comment by qzminski** [comment]
I have just released version 2.0.0 which supports the new API. Please be sure to read the documentation before you upgrade as there have been major some changes!
