### ISSUE TITLE
Long-Lived Tokens

### ISSUE THREAD

**Issue by ngdot** [codefog/contao-instagram#17]
Es gibt wohl nun Long-Live Tokens: https://developers.facebook.com/docs/instagram-basic-display-api/guides/long-lived-access-tokens

**Comment by ngdot** [comment]
Scheint zu klappen, habe mir manuell aus meinem short-lived token gerade einen long-lived token erstellt der 60 Tage gültig ist.

**Comment by fritzmg** [comment]
Es gibt auch Access Tokens, die nie ablaufen. Siehe zB folgende Anleitung: https://github.com/fritzmg/contao-facebook-gallery/#access-token

**Comment by qzminski** [comment]
@ngdot I will implement them as soon as they are stable. Right now they are in beta phase.

@fritzmg that certainly works for Facebook, but does it also work for Instagram?

**Comment by fritzmg** [comment]
Doesn't Instagram use the Facebook Graph API now?

**Comment by qzminski** [comment]
Not exactly I think. It is somewhat similar but has different endpoints and features than Graph API.

**Comment by fritzmg** [comment]
Ah ok, didn't realize :)

**Comment by ngdot** [comment]
@qzminski Long-Lived Access Tokens are now stable.
https://developers.facebook.com/docs/instagram-basic-display-api/changelog

**Comment by qzminski** [comment]
@ngdot thanks for the info, I will implement it as soon as I find some spare time.

**Comment by qzminski** [comment]
Version 2.1.0 has been just released 👍🏻
