### ISSUE TITLE
Feed doesn't update on new Insta-Post

### ISSUE THREAD

**Issue by janoschbatschi** [codefog/contao-instagram#19]
Unfortunately it is still necessary to request a new access token to get the newest post - can anybody reproduce this?

Contao: 4.4.45
contao-instagram: 2.10

**Comment by janoschbatschi** [comment]
Correct me if I'm wrong, but using long-lived tokens the feed should be updated whenever a change on Instagram occurs, shouldn't it? Or is it still necessary to request a new token on every new post?

**Comment by qzminski** [comment]
I have fixed it in 2.1.1. Please update your packages. The cache timeout can now be adjusted in the app configuration file, see the README for more details.

**Comment by janoschbatschi** [comment]
It seems to be a problem with the updated version 2.1.1. When trying to update the error below is occuring. Even removing the whole package and a reinstallation throws the same error, while other packages are updating without a problem.

In ScriptHandler.php line 113:
                                                                           
An error occurred while executing the "contao:install-web-dir" command:  
                                                                           

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>...]


# Process terminated with exit code 1
# Result: General error

**Comment by qzminski** [comment]
Hey @janoschbatschi can you please check the `/var/logs/` folder for any errors?

**Comment by janoschbatschi** [comment]
Just updated another package to confirm the error being related to this package. 

So the logs say:

```
[2020-03-23 12:11:52] request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_url_fragment":"contao-manager/users.json","_route":"contao_catch_all"},"request_uri":"https://xxxxxx.tld/contao-manager/users.json","method":"GET"} []
[2020-03-23 12:11:52] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2020-03-23 12:11:52] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: https://xxxxxx.tld/contao-manager/users.json" at /xxxx/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: https://xxxxxx.tld/contao-manager/users.json at /xxxx/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: https://xxxxxx.tld/contao-manager/users.json at /xxxx/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:63)"} []
```

while the detailed console output being: 

> contao/manager-plugin: Generating plugin class...
> contao/manager-plugin: ...done generating plugin class
> Loading composer repositories with package information
> Installing dependencies from lock file
> Package operations: 0 installs, 6 updates, 0 removals
>   - Updating symfony/symfony (v3.4.37 => v3.4.38): Loading from cache
>   - Updating doctrine/reflection (v1.1.0 => 1.2.0): Loading from cache
>   - Updating doctrine/persistence (1.3.6 => 1.3.7): Loading from cache
>   - Updating symfony/http-client (v5.0.4 => v5.0.5): Loading from cache
>   - Updating scssphp/scssphp (1.0.7 => 1.0.8): Loading from cache
>   - Updating codefog/contao-instagram (2.1.0 => 2.1.1): Loading from cache
> Generating optimized autoload files
> > Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
> Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
> 
> In ScriptHandler.php line 113:
>                                                                            
>   An error occurred while executing the "contao:install-web-dir" command:  
>                                                                            
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>...]
> 
> 
> # Process terminated with exit code 1
> # Result: General error

**Comment by qzminski** [comment]
Can you run the below command using SSH? It should give more details about the error.

```
php vendor/bin/contao-console contao:install-web-dir -vvv
```

**Comment by janoschbatschi** [comment]
thx for the fast reply - unfortunately I don't have SSH access on this particular webspace

**Comment by qzminski** [comment]
I am not able to reproduce the problem you are having. Theoretically the version 2.1.1 should have absolutely no impact on `contao:install-web-dir` command. Try to install (not update) dependencies using Contao Manager and see if the error occurs again.

**Comment by qzminski** [comment]
@janoschbatschi please try version 2.1.2. See https://github.com/codefog/contao-instagram/issues/21 for further details.

**Comment by janoschbatschi** [comment]
Thank you very much! This update worked flawlessly. I'll let you know, if the feed doesn't update on a new post as expected.
