### ISSUE TITLE
Add "thumbnail_url" to Media Data Fields

### ISSUE THREAD

**Issue by MarkejN** [codefog/contao-instagram#24]
Hello, I just updated to the newest version and noticed that it is now possible to get video media. Can you add ["thumbnail_url"](https://developers.facebook.com/docs/instagram-api/reference/media/#metadata) to the list of fields in the following line, so that it is possible to use them as video posters?

https://github.com/codefog/contao-instagram/blob/85527dcf1dbfc07095ac7900fc47482dd730057e/src/InstagramClient.php#L96

**Comment by qzminski** [comment]
I have just released 2.1.4 that should fix this issue.
