### ISSUE TITLE
preview images hosted by Contao for instagram media types VIDEO & CAROUSEL_ALBUM

### ISSUE THREAD

**Issue by Metis77** [codefog/contao-instagram#25]
Now that video & carousels are included, we would love to have also preview images of those types in Contao.
So we do not need to load the preview images external from instagram.

if "media_type" => "VIDEO" the is a preview image in "thumbnail_url"
if "media_type" => "CAROUSEL_ALBUM" the is the first image in "media_url"

would it be possible to download those images to Contao and use them just as we can use the images of the normal image posts?

**Comment by qzminski** [comment]
Implemented in 29fa903.

**Comment by qzminski** [comment]
I have just released 2.2.0 :+1:
