### ISSUE TITLE
uploaded video destroys instagram widget

### ISSUE THREAD

**Issue by pagestyles** [codefog/contao-instagram#27]
Hi,
my customer uploaded a video to his instagram account, now the video is written to the src="" attribute without any query and destroys the feed:

<img width="437" alt="Bildschirmfoto 2020-07-10 um 19 09 13" src="https://user-images.githubusercontent.com/6087840/87180825-8f8c7b00-c2e1-11ea-9c4a-dccd84e4d64b.png">
<img width="391" alt="Bildschirmfoto 2020-07-10 um 19 18 42" src="https://user-images.githubusercontent.com/6087840/87181219-36711700-c2e2-11ea-939c-154dc48b65c3.png">

is there any way to treat them separately or sort them out?

**Comment by qzminski** [comment]
That's strange, can you show your output of `<?php $this->showTemplateVars(); ?>` ?

**Comment by pagestyles** [comment]
hi, sure:

<img width="3095" alt="Bildschirmfoto 2020-07-14 um 08 23 11" src="https://user-images.githubusercontent.com/6087840/87391741-96e6a980-c5ab-11ea-870a-c5a38478be01.png">


I tried to get the rest of the array into a .txt:
[contao-instagram_error2.txt](https://github.com/codefog/contao-instagram/files/4916938/contao-instagram_error2.txt)

**Comment by qzminski** [comment]
Should be fixed in 2.2.0 that I have just released. You may need to adjust your custom template, if any (see aee4b2d).
