### ISSUE TITLE
An unexpected error has occured

### ISSUE THREAD

**Issue by chris74656** [codefog/contao-instagram#28]
Hi!

I installed contao-instagram, set it all up and it seemed to work just fine.
It retrieved the Access Token and the frontend module displayed postings from IG on the website.
A few hours later i started getting this error in the Contao log whenever i open the page with the module...

> Unable to fetch Instagram data from "https://graph.instagram.com/me/media": Server error: `GET https://graph.instagram.com/me/media?access_token=TokenReplacedByMe&fields=id%2Ccaption%2Cmedia_type%2Cmedia_url%2Cpermalink%2Cthumbnail_url%2Ctimestamp` resulted in a `500 Internal Server Error` response: {"error":{"message":"An unexpected error has occurred. Please retry your request later.","type":"OAuthException","is_tra (truncated...)

...and the content element is not displayed at all on the page.

I thought maybe the token had expired so i request a new one, which worked but didn't solve the problem.
Not sure if this is a problem with Instagram or contao-instagram because of the error code 500. Is anyone else getting this?

**Comment by qzminski** [comment]
@chris74656 does the error still happen?
