### ISSUE TITLE
Unregelmäßiger Bug bei Videoanzeige

### ISSUE THREAD

**Issue by dakitec** [codefog/contao-instagram#31]
In unregelmäßigen Zeitabständen haben wir das Problem, dass ein Video nicht angezeigt wird, obwohl der dahinterstehende Videolink, der im <img src=""> eingebunden war, auch existiert und aufrufbar war. Stattdessen wird dann nur das Alt-Tag angezeigt.

Videolink: https://video-frt3-1.cdninstagram.com/v/t50.2886-16/118633703_166666808364791_7009581503262965843_n.mp4?_nc_cat=110&vs=17900449870540708_1550760412&_nc_vs=HBkcFQAYJEdPYzBFZ2YzanVnamxaY0FBRk5BSXlZOUNVZGhia1lMQUFBRhUAAsgBACgAGAAbAYgHdXNlX29pbAExFQAAGAAWyPqom6iXzD8VAigCQzMsF0AkAAAAAAAAGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHXqBwA%3D&_nc_sid=59939d&efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5mZWVkIn0%3D&_nc_ohc=HB0RXSbaUBoAX98S_fG&_nc_ht=video-frt3-1.cdninstagram.com&oh=d93995640ea40e546203a0e1f4916d57&oe=5F9B1B8E&_nc_rid=a5ae835cc2

Es handelt sich um die Seite: https://beefriendly-earth.de
PHP Version: 7.4.10
Contao Version: 4.4.48
Codefog/Contao-Instagram Version: 2.1.2

**Comment by qzminski** [comment]
Sorry, I don't speak German. Can you submit your issue in English?

**Comment by dakitec** [comment]
Sorry, I didn't know that. Let me try to translate it:

At irregular intervals we have the problem that videos are not shown. Instead it just shows the "alt"-tag like if the video was not found. But the strange thing is, if you copy & paste the video link that is in <img src="xxx"> to the browser, it works fine:

Link of a video: https://video-frt3-1.cdninstagram.com/v/t50.2886-16/118633703_166666808364791_7009581503262965843_n.mp4?_nc_cat=110&vs=17900449870540708_1550760412&_nc_vs=HBkcFQAYJEdPYzBFZ2YzanVnamxaY0FBRk5BSXlZOUNVZGhia1lMQUFBRhUAAsgBACgAGAAbAYgHdXNlX29pbAExFQAAGAAWyPqom6iXzD8VAigCQzMsF0AkAAAAAAAAGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHXqBwA%3D&_nc_sid=59939d&efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5mZWVkIn0%3D&_nc_ohc=HB0RXSbaUBoAX98S_fG&_nc_ht=video-frt3-1.cdninstagram.com&oh=d93995640ea40e546203a0e1f4916d57&oe=5F9B1B8E&_nc_rid=a5ae835cc2

(this link works, but sometimes it doesn't work on our page)

This is our page: https://beefriendly-earth.de (on the bottom you can find the instagram module included)
PHP version: 7.4.10
Contao version: 4.4.48
Codefog/Contao-Instagram version: 2.1.2

Also it seems like when it is happening, it is on all browsers.

**Comment by qzminski** [comment]
It looks like the video itself is displayed as image source and that is the problem. Please update the extension as stated in https://github.com/codefog/contao-instagram/issues/27#issuecomment-658015667, adjust the template and that should solve the problem.

**Comment by qzminski** [comment]
Duplicate #27.
