### ISSUE TITLE
Invalid scope

### ISSUE THREAD

**Issue by dakitec** [codefog/contao-instagram#32]
Hi, basically this bundle works well for me. But from time to time the images stop appearing. I tried to get a new access token, but I always get this error:

`{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: []"}`

What can I do to fix that?

Thank you,

Best regards,
Daniel

**Comment by dakitec** [comment]
Thanks for your help. I am on version 2.2.1 (8/3/2020, 5:27:22 PM). Earlier I set it up in a previous version, but I am not sure how to find out which version that was. The strange thing is that it just stopped working without any change as far as I know.

**Comment by qzminski** [comment]
Did you set the things up according to the recent documentation? https://github.com/codefog/contao-instagram/tree/master/docs

I would like you to double check that because if you have set it up in some older version of the extension, this may cause issues now.

**Comment by dakitec** [comment]
@qzminski Thanks for your help. I double checked all and it was setup fine. What I did now was reinstalling the plugin and re-authorize the token. This worked. But I am really unsure, why it stopped working. Maybe a change from Instagram, I don't know.
