### ISSUE TITLE
cURL error if instagram is down

### ISSUE THREAD

**Issue by hh-com** [codefog/contao-instagram#34]
The module does not catch the cURL error if instagram ist not reachable.

request.CRITICAL: Uncaught PHP Exception GuzzleHttp\Exception\ConnectException: "cURL error 6: Could not resolve host: graph.instagram.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)" at /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 200 {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 6: Could not resolve host: graph.instagram.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200)"} []

**Comment by fritzmg** [comment]
> Could not resolve host: graph.instagram.com

Facebook had a major outage yesterday. Their nameserver went down for several hours. It should work again, but it appears your DNS cache is not updated yet.

**Comment by qzminski** [comment]
This should be definitely caught and not crash the whole page the module is on. I'll take care of it in the next hotfix release.
