### ISSUE TITLE
Error while setting up on Contao 4.13.4

### ISSUE THREAD

**Issue by johannes-bittner** [codefog/contao-instagram#37]
When I try to request the access token (fresh install), I am redirected to Instagram; then I allow the app to share information, and after clicking on "Allow", I get redirected to my installation where the following error is displayed: 

`Attempted to call an undefined method named "fetchAssoc" of class "Doctrine\DBAL\Connection". Did you mean to call "fetchAssociative"?
`

`Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "fetchAssoc" of class "Doctrine\DBAL\Connection". Did you mean to call "fetchAssociative"?" at /var/www/vhosts/client/httpdocs/contao-4-13/vendor/codefog/contao-instagram/src/Controller/InstagramController.php line 92
{
    "exception": {}
}`

Stack trace:

> Symfony\Component\ErrorHandler\Error\UndefinedMethodError:
> Attempted to call an undefined method named "fetchAssoc" of class "Doctrine\DBAL\Connection".
> Did you mean to call "fetchAssociative"?
> 
>   at vendor/codefog/contao-instagram/src/Controller/InstagramController.php:92
>   at Codefog\InstagramBundle\Controller\InstagramController->authAction()
>      (vendor/symfony/http-kernel/HttpKernel.php:152)
>   at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
>      (vendor/symfony/http-kernel/HttpKernel.php:74)
>   at Symfony\Component\HttpKernel\HttpKernel->handle()
>      (vendor/symfony/http-kernel/Kernel.php:202)
>   at Symfony\Component\HttpKernel\Kernel->handle()
>      (web/index.php:44)

Changing "fetchAssoc" to "fetchAssociative" in vendor/codefog/contao-instagram/src/Controller/InstagramController.php line 92 solved the problem for me.

**Comment by qzminski** [comment]
Thank you, released in 2.3.2.

**Comment by johannes-bittner** [comment]
I thank *you* !
