### ISSUE TITLE
Refresh instagram access token with cronjob

### ISSUE THREAD

**Issue by falkgeist** [codefog/contao-instagram#40]
At the moment, long-lived instagram tokens expire after 60 days, making it necessary to create a new token about every two months. This is tedious, tbh.

Is there a possiblity to add a cronjob to the bundle, that refreshes the token after e.g. 30 days via the corresponding endpoint of the Basic Display API?

[Long lived access tokens](https://developers.facebook.com/docs/instagram-basic-display-api/guides/long-lived-access-tokens/)

We already got several clients calling, asking why the feed is not showing posts anymore...

Thank you very much!

**Comment by fritzmg** [comment]
> Is there a possiblity to add a cronjob to the bundle, that refreshes the token after e.g. 30 days via the corresponding endpoint of the Basic Display API?
> 
> [Long lived access tokens](https://developers.facebook.com/docs/instagram-basic-display-api/guides/long-lived-access-tokens/)

This requires a short lived access token which in turn requires a login. As far as I understand it, Facebook does not allow you to infinitely extend a long lived access token without authorization anymore.

If there _is_ a way I would also be curious to know how it works :)

**Comment by falkgeist** [comment]
Yes, exactly, `GET /refresh_access_token`, sorry, should have mentioned that. How difficult would it be for you to implement that?

**Comment by falkgeist** [comment]
I'm sorry to remind about this, I would create a PR, but I'm sure until I figure out how to implement the cronjob for the token refresh, you would've implemented it already in a third of that time.

**Comment by fritzmg** [comment]
If you cannot provide the PR yourself - and you are in need of this feature, then you should hire someone. Either the original creator of this extension or someone else.

**Comment by falkgeist** [comment]
Maybe @qzminski will see this, but I will try to find the time to fork this project and add the necessary cronjob 👍. I was under the impression you are more involved with this bundle, sorry, only checked your contributions now.

**Comment by qzminski** [comment]
I do see this and I will introduce it at some point, but I currently have no time to work on the open source projects.
