### ISSUE TITLE
Missing auto update of posts inside Instagram Feed [Frontend Module]

### ISSUE THREAD

**Issue by githuppi** [codefog/contao-instagram#43]
Hello Kamil,

we want to use your extension in a new Contao 4.13.38 project. I had installed the extension (Version 2.3.5) a couple of weeks ago and are currently wondering why the feed won't be updated. Since than a couple of postings were made on Instagram. But in the frontend I can only see data from the past.

Did I miss to configure an update trigger?

Kind regards
Dennis

Within the config.yml I have:

```codefog_instagram:
    access_token_ttl: 28800 # 8h access token local time to live after which Contao will make a request to refresh the token, in seconds
    cache_ttl: 1800 # 30 min feed data cache local time to live, in seconds

**Comment by janborg** [comment]
is it not updated at all, or is it updated too late? see #46

**Comment by qzminski** [comment]
Please try updating to version 2.4.2.

**Comment by githuppi** [comment]
We have a client where we use the latest version and it's working as expected.
