### ISSUE TITLE
Contao 5 support

### ISSUE THREAD

**Issue by leon1995** [codefog/contao-instagram#44]
Will there be support for contao 5?

**Comment by qzminski** [comment]
Yes, but it's unclear when exactly. If you need it urgently, please contact us at info@codefog.pl and maybe we can find a solution in a timely fashion.

**Comment by Deitsch** [comment]
Also looking for Contao 5 support. @qzminski is there a roadmap by now?

**Comment by fritzmg** [comment]
@Deitsch see the previous answer. You can also contract another developer to create a PR.

**Comment by qzminski** [comment]
I have just released a new version 2.5.0 which is compatible with Contao 5.3.
