### ISSUE TITLE
Module not working anymore because instagram changed the api calls

### ISSUE THREAD

**Issue by kaipk** [codefog/contao-instagram#6]
instagram changed the api and now the module is not working anymore. see -> https://www.instagram.com/developer/changelog/ - some endpoints are deprecated.

ps: your module is great

i think you can fix it like that

in InstagramModule.php line 91

....
```
 /*if (($userId = $this->fetchUserId()) === null) {
            return [];
  }*/

//fetchUserId not neccecary now, because instagram allows only self data

$response = $this->sendRequest(sprintf('https://api.instagram.com/v1/users/self/media/recent', $userId), ['count' => $this->numberOfItems]);
```
.....

**Comment by fritzmg** [comment]
Did you test that fix? If yes, create a PR ;)

**Comment by kaipk** [comment]
yes, here is my pull request #7

**Comment by qzminski** [comment]
Thanks, closing this one in favor of #7 then.
